[package]
name = "gigglechat-irc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
iroh = "0.90.0"
# rand = "0.9.1"
tokio = "1.46.0"
rand = { version = "0.8", features = ["std", "std_rng"] }
iroh-gossip = "0.90.0"
futures-lite = "2.6.0"
